### ISSUE TITLE
[MV] "Cannot read property of 'replace' of undefined." error (plugin command: rpc_replaceRow)

### ISSUE THREAD

**Issue by YoBroSkiies** [00due/Discord-RPC-for-RMMZ#5]
**CHECKLIST**

I've updated nwjs to 0.49.2 or higher: ✅
I've installed the `discord-rpc` node module: ✅
There's a `node_modules` folder in my project directory: ✅

**Describe the bug**
When using `rpc_replaceRow1` OR `rpc_replaceRow2`, the game will throw an error stating it "Cannot read property of 'replace' of undefined."

**To Reproduce**
1. Install all pre-requisites. Set a text string in the plugin parameter for Row 1 or 2.
2. Created a plugin command in an event to replace a certain row (rpc_replaceRow1 OR rpc_replacerow2) followed by a string of text.
3. Error immediately occurs when the event executes the plugin command.

**Expected behavior**
Discord RPC should report the default text set within the plugin. Upon using the plugin command "`rpc_replaceRow`" (1 or 2) it should update according to the text string inputted.

**Screenshots**
![image](https://github.com/00due/Discord-RPC-for-RMMZ/assets/86446595/ee9968f1-86fa-435d-bcca-ff84fc91bbdc)
![image](https://github.com/00due/Discord-RPC-for-RMMZ/assets/86446595/fda98677-6f01-409c-98c7-f44a47680a1b)
![image](https://github.com/00due/Discord-RPC-for-RMMZ/assets/86446595/7c5805c9-7afb-448e-ac18-432071b0934b)
![image](https://github.com/00due/Discord-RPC-for-RMMZ/assets/86446595/aa0549e1-f87f-438f-b871-e04eb4977f51)

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin version: 1.2

**Additional context**
Just bonus content to be patched as well:
- Line 208 & 210 are missing "discord" in front of "parameters". Without "discord" in front I got errors, but after filling in the code, it works just fine.

**Comment by 00due** [comment]
Sorry about that. The previous issue you got was because I copy-pasted the 1.2 source code from MZ version which uses the variable `parameters` instead of `discordParameters`.

Yesterday then I just lazily replaced everything starting with `parameters[`, and didn't remember those two. I'll fix this soon.

**Comment by YoBroSkiies** [comment]
No worries! It'll be good to patch out the parameters issue, but the main point of the bug/issue log is something to do a different line of code involving the plugin command.
The `discordParameters` issue doesn't seem to directly affecr this one...

**Comment by 00due** [comment]
I've made an update to another branch to see if it works now.

Link: https://github.com/00due/Discord-RPC-for-RMMZ/archive/refs/heads/test.zip

**Comment by YoBroSkiies** [comment]
Two things:
First: Error shows up:
![image](https://github.com/00due/Discord-RPC-for-RMMZ/assets/86446595/f7e8abd9-8e5e-464c-886e-287f1d1756a5)

Second: The `replaceRow1` & `replaceRow2` code look to be mixed in code.
![image](https://github.com/00due/Discord-RPC-for-RMMZ/assets/86446595/9099748f-bb85-474e-a05c-fef6727f12a3)
Unsure if intentional, but both lines contain `args.row1`
The code is also failing to defined 'args' 
I'll see if I can read the code and try do some editing on my behalf.

**Comment by 00due** [comment]
I updated it once again.

Sorry for all this, but I can't test the MV version, since I only own MZ. Because of that, I don't know if the code will work or not.

**Comment by 00due** [comment]
Okay, I saw another issue there. I've updated it again.

**Comment by YoBroSkiies** [comment]
That's more than okay! I'm happy to keep posting logs if you're happy to keep troubleshooting!
As of now, it looks like you done it!
![image](https://github.com/00due/Discord-RPC-for-RMMZ/assets/86446595/dd335afc-b9ce-49f5-87dd-80cbce5ddbbb)
![image](https://github.com/00due/Discord-RPC-for-RMMZ/assets/86446595/22cea94f-5d6b-42d7-a594-8be723ad128b)

nicely done!! c:
